### PR TITLE
Upgrade deps

### PR DESCRIPTION
**Pull request by grigorii-horos**
Now marked-terminal supports hyperlinks

### CODE REVIEW

**Comment by finnp** [comment]
thank you! Are you interested in mainting this? I don't use it that much. Probably doesn't need that much work. But I can add you on github and npm so you can publish new versions yourself.

**Comment by grigorii-horos** [comment]
@finnp It will be good.

**Comment by grigorii-horos** [comment]
@finnp Can you transfer ownership to me or give me access to this repo? I would like to fix some bugs and add some features.

**Comment by finnp** [comment]
@horosgrisa I added you as a collaborator. I hope that's enough. Do you have access to npm?

**Pull request merged**
